In [ ]:
import numpy as np
l1=[2,3,4,5,6,7,8]
a=np.array(l1)
print(a)

[2 3 4 5 6 7 8]


In [ ]:
a.shape

(7,)

In [ ]:
type(a)

numpy.ndarray

my_list=[4,5,6,7,8]
my_list2=[-2,6,8,3,4]
my_list3=[5,6,0,-3,5]
convert these list into a multinested array and fetch given rows and columns.
1.arr=[0:2,2:]

In [ ]:
import numpy as np
my_list=[4,5,6,7,8]
my_list2=[-2,6,8,3,4] 
my_list3=[5,6,0,-3,5]
arr=np.array([my_list,my_list2,my_list3])
print(arr)

[[ 4  5  6  7  8]
 [-2  6  8  3  4]
 [ 5  6  0 -3  5]]


In [ ]:
print(arr[0:2,1:2])

[[5]
 [6]]


In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.random.rand(4,5)

array([[0.71734064, 0.96637789, 0.81195354, 0.89382902, 0.19212967],
       [0.07608832, 0.60313428, 0.56305956, 0.22836851, 0.41237667],
       [0.97231995, 0.45448556, 0.88835784, 0.35631796, 0.81581053],
       [0.98588038, 0.34405613, 0.07944679, 0.11367405, 0.82927251]])

In [ ]:
np.random.randint(3,4,5)

array([3, 3, 3, 3, 3])

In [ ]:
import numpy as np
np.arange(3,5)

array([3, 4])

In [ ]:
import numpy as np
np.linspace(4,5,55)

array([4.        , 4.01851852, 4.03703704, 4.05555556, 4.07407407,
       4.09259259, 4.11111111, 4.12962963, 4.14814815, 4.16666667,
       4.18518519, 4.2037037 , 4.22222222, 4.24074074, 4.25925926,
       4.27777778, 4.2962963 , 4.31481481, 4.33333333, 4.35185185,
       4.37037037, 4.38888889, 4.40740741, 4.42592593, 4.44444444,
       4.46296296, 4.48148148, 4.5       , 4.51851852, 4.53703704,
       4.55555556, 4.57407407, 4.59259259, 4.61111111, 4.62962963,
       4.64814815, 4.66666667, 4.68518519, 4.7037037 , 4.72222222,
       4.74074074, 4.75925926, 4.77777778, 4.7962963 , 4.81481481,
       4.83333333, 4.85185185, 4.87037037, 4.88888889, 4.90740741,
       4.92592593, 4.94444444, 4.96296296, 4.98148148, 5.        ])

In [ ]:
import numpy as np
np.random.rand(3,4)


array([[0.24741887, 0.98202212, 0.24431216, 0.41562916],
       [0.71112045, 0.94054869, 0.37825022, 0.06363786],
       [0.55044221, 0.09770266, 0.25890315, 0.2844595 ]])

In [ ]:
import numpy as np
np.random.randint(4,5,6)

array([4, 4, 4, 4, 4, 4])